apiVersion: v1
kind: Namespace
metadata:
  name: gitops
spec:
  template:
    spec:
      containers:
        - image: null
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops
  namespace: gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops
  template:
    metadata:
      labels:
        app: gitops
    spec:
      containers:
        - name: gitops
          image: >-
            dlcksdnd6785/gitops:1817f87d
          command:
            - /bin/sh
          args:
            - '-c'
            - npm start
          ports:
            - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: gitops
  namespace: gitops
spec:
  type: NodePort
  ports:
    - port: 81
      targetPort: 3003
      nodePort: 30000
  selector:
    app: gitops
  template:
    spec:
      containers:
        - image: null
